import { ViewTransitions } from 'next-view-transitions'

import { Header } from '@/components/header'
import { ThemeProvider } from '@/components/theme'

import type { Metadata } from 'next'
import '@/style/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ViewTransitions>
      <html lang="en" suppressHydrationWarning>
        <body>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Header />
            <main>{children}</main>
          </ThemeProvider>
        </body>
      </html>
    </ViewTransitions>
  )
}
